### PR TITLE
Add the slack link to the community menu button

### PR DESCRIPTION
**Pull request by BosEriko**
I couldn't find a section, only a link on the menu. I updated that one.

### CODE REVIEW

**Comment by briansanger** [comment]
Maybe a trivial question. I know bit.ly links are usually permanent but would it be better to use the actual slack URL in this context?

https://openfloodai.slack.com

**Comment by BosEriko** [comment]
makes sense. I updated the PR and also added a target="_blank".

The reason for adding a target="_blank" for me is that if a person visited the site and what they do first is click the slack link, they will be considered as a bouncing user which is bad for SEO.

at least that was the case when I last read an SEO book.

**Comment by BosEriko** [comment]
@adventuroussrv what do you think? are you fine with having it as target="_blank"? If you want it removed just say so.

**Comment by ghost** [comment]
Sounds good for now! @BosEriko merging it! 

We are looking for more awesome suggestions like this! 
you may keep in touch or join the slack! @n0madzer0 @BosEriko

**Pull request merged**
