### PR TITLE
Rajkumar

### PR DESCRIPTION
**Pull request by RajkumarMittal**
I have improved your (navbars) before improvement it cuts the navbar when we short the screen now after improvement navbars get collapsed and now we are able to use them even after the shorting the screen.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @RajkumarMittal can you make PR to dev branch again!
I'm not able to resolve merge conflicts from my side!

**Comment by RajkumarMittal** [comment]
okay @adventuroussrv

**Comment by RajkumarMittal** [comment]
have you changed the project look its not the same as it was earlier @adventuroussrv

**Comment by ghost** [comment]
yes! @RajkumarMittal the issue was assigned to @greg  earlier he and he made the pr according to the issue!

**Pull request closed without merging**
