### PR TITLE
dark footer created

### PR DESCRIPTION
**Pull request by abhilakshyadobhal**
dark footer created and social icons color will change while hovering over them.
Screenshot from 2019-10-05 15-07-34

### CODE REVIEW

**Comment by abhilakshyadobhal** [comment]
If you like it pls merge it

**Comment by ghost** [comment]
Hi, We have already got the PR for it! Thanks

**Comment by abhilakshyadobhal** [comment]
ok sorry

**Comment by ghost** [comment]
Hi @abhilakshyadobhal It's completely okay! Happy Coding.

**Pull request closed without merging**
